apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: student-app

spec:

  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

        - name: backend

          image: sujeetsr07/student-task-backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          resources:

            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          livenessProbe:

            httpGet:
              path: /api/health
              port: 5000

            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:

            httpGet:
              path: /api/health
              port: 5000

            initialDelaySeconds: 5
            periodSeconds: 5
