apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: student-app

spec:

  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:

    metadata:
      labels:
        app: frontend

    spec:

      containers:

        - name: frontend

          image: sujeetsr07/student-task-frontend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 80

          resources:

            requests:
              cpu: "100m"
              memory: "64Mi"

            limits:
              cpu: "300m"
              memory: "128Mi"

          livenessProbe:

            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:

            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 5
            periodSeconds: 5